<a href="https://colab.research.google.com/github/woodRock/grokking-deep-learning/blob/main/chapter_3_forward_propagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter 3 | Forward Propagation

## First Neural Network

In [ ]:
weight = 0.1

def neural_network(input, weight):
    prediction = input * weight 
    return prediction 

number_of_toes = [8.5, 9.5, 10, 9]
input = number_of_toes[0]
pred = neural_network(input,weight)
print(pred)

0.8500000000000001


## Vector Math

In [10]:
def elementwise_multiplication(vec_a, vec_b): 
    return [i*j for i,j in zip(vec_a, vec_b)]


def elementwise_addition(vec_a, vec_b):
    """ Elementwise addition of two vectors."""
    return [i+j for i,j in zip(vec_a,vec_b)]


def vector_sum(vec_a):
    """ The sum of a vector.""" 
    return sum(vec_a)


def vector_average(vec_a): 
    """ The average value of a vector."""
    n = len(vec_a)
    return vector_sum(vec_a) / n


def vector_dot_product(vec_a, vec_b):
    """ The sum of the elementwise multiplication of two vectors."""
    return vector_sum(elementwise_multiplication(vec_a, vec_b))

# Unit tests for the functions defined about. 
assert elementwise_multiplication([1,2],[1,1]) == [1,2]
assert elementwise_addition([1,1],[1,1]) == [2,2]
assert vector_sum([1,2,3]) == 6
assert vector_average([1,1,1]) == 1
assert vector_dot_product([1,1,1], [2,2,2]) == 6

## Multiple Inputs | Crude

In [17]:
def w_sum(a,b):
    """ The weighted sum of two vectors. """
    assert(len(a) == len(b))
    return sum([a[i] * b[i] for i in range(len(a))])

weights = [0.1, 0.2, 0]

def neural_network(inputs, weights):
    pred = w_sum(inputs, weights)
    return pred 

toes = [8.5, 9.5, 9.9, 9.0]
wlred = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

inputs = [toes[0], wlred[0], nfans[0]]
pred = neural_network(inputs,weights)
print(pred)

0.9800000000000001


## Multiple Inpputs | NumPy

In [20]:
import numpy as np 

weights = np.array([0.1, 0.2, 0])

def neural_network(inputs, weights):
    pred = inputs.dot(weights)
    return pred 

toes = np.array([8.5, 9.5, 9.9, 9.0])
wlred = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

inputs = np.array([toes[0], wlred[0], nfans[0]])
pred = neural_network(inputs,weights)
print(pred)

0.9800000000000001


## Hidden Layers

Neural networks can be stacked. You can take the output of one network and fet it as input into another network. This results in two consectuvie vector-matrix mulitplications. Layers added between the input and output layers are referred to as hidden layers. Hidden layers help a network learn patterns that are too cimplex for a single-weight matrix. 

In [22]:
import numpy as np 

ih_wgt = np.array([
                   [0.1, 0.2, -0.1],
                   [-0.1, 0.1, 0.9],
                   [0.1, 0.4, 0.1]
                   ]).T 

hp_wgt = np.array([
                   [0.3, 1.1, -0.3],
                   [0.1, 0.2, 0.0],
                   [0.0, 1.3, 0.1]
]).T

weights = [ih_wgt, hp_wgt]

def neural_network(input, weights): 
    hidden = input.dot(weights[0])
    pred = hidden.dot(weights[1])
    return pred 

toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

input = np.array([[toes[0], wlrec[0], nfans[0]]])
pred = neural_network(input,weights)
print(pred)

[[0.2135 0.145  0.5065]]


## Numpy Primer

In [31]:
import numpy as np 

a = np.array([0,1,2,3]) # Vector 
b = np.array([4,5,6,7]) # Vector
c = np.array([[0,1,2,3], 
              [4,5,6,7]]) # Matrix 

d = np.zeros((2,4)) # 2x4 matrix of zeros. 
e = np.random.rand(2,5) # Random 2x5 matrix of numbers between 0 and 1 

# print(a)
# print(b)
# print(c)
# print(d)
# print(e)

print(a * 0.1) # Multiplies ever number in vector by 0.1  
print(c * 0.1) # Multiplies every number in matrix c by 0.1 
print(a * b) # Multiplies elementwise between a and b (columns paired). 
print(a * b * 0.1) # Multiplies elementwise, then by 0.2
print(a * c) # Performs elementwise multiplication on every row of matrix c, because c has the same number of columns as a. 
print(a * e) # Throws an error, because a and e don't have the same number of columns. 

[0.  0.1 0.2 0.3]
[[0.  0.1 0.2 0.3]
 [0.4 0.5 0.6 0.7]]
[ 0  5 12 21]
[0.  0.5 1.2 2.1]
[[ 0  1  4  9]
 [ 0  5 12 21]]


ValueError: ignored

There's on golden rule when using the `dot` function: if you put the `(rows,columns)` description of the two variables you're "dotting" next ot each other, neighbouring numbers should always be the same. In this case, you're dot-producing (1,4) with (4,3). It works fine and outputs (1,3). In order to perform matrix multiplication, between to matrices A and B, the columns of matrix A, must equal the rows of matrix B. This even applies to vectors as a matrix of shape (1,x), where x is the length of the vector. This allows us to multiply a vector by a matrix. 

In [40]:
a = np.zeros((1,4))
b = np.zeros((4,3))
c = a.dot(b)
print(c.shape)

e = np.zeros((2,1))
f = np.zeros((1,3))
g = e.dot(f)
print(g.shape)

h = np.zeros((5,4)).T # T is the tranpose operator, this flips the rows and columns of a matrix. See (Goodfellow 2016) Linear Algebra for more rigirous mathematical definition. 
i = np.zeros((5,6))
j = h.dot(i)
print(j.shape)

h = np.zeros((5,4)) # Without transpose columns of h != rows of i
i = np.zeros((5,6))
j = h.dot(i) # Throws an error
print(j.shape) 

(1, 3)
(2, 3)
(4, 6)


ValueError: ignored